# Generated by Django 4.1.6 on 2023-03-01 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("post_text", models.CharField(max_length=140)),
                ("pub_date", models.DateTimeField(verbose_name="date posted")),
                ("likes", models.IntegerField(default=0)),
            ],
        ),
    ]
