# Generated by Django 4.1.6 on 2023-03-07 07:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("posts", "0003_chatroom"),
    ]

    operations = [
        migrations.RemoveField(model_name="chatroom", name="users",),
        migrations.AddField(
            model_name="chatroom",
            name="users",
            field=models.ManyToManyField(
                null=True, related_name="chatrooms", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
