# Generated by Django 4.1.6 on 2023-03-07 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0005_alter_chatroom_users"),
    ]

    operations = [
        migrations.RemoveField(model_name="chatroom", name="users",),
        migrations.AddField(
            model_name="chatroom",
            name="posts",
            field=models.ManyToManyField(related_name="chatrooms", to="posts.post"),
        ),
    ]
