# Generated by Django 4.1.6 on 2023-03-09 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0006_remove_chatroom_users_chatroom_posts"),
    ]

    operations = [
        migrations.RemoveField(model_name="chatroom", name="posts",),
        migrations.CreateModel(
            name="Chatroom_Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chatrooms",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="posts.chatroom"
                    ),
                ),
                (
                    "posts",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="posts.post"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="post",
            name="chatrooms",
            field=models.ManyToManyField(
                related_name="posts", through="posts.Chatroom_Post", to="posts.chatroom"
            ),
        ),
    ]
