# Generated by Django 4.1.6 on 2023-03-14 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0007_remove_chatroom_posts_chatroom_post_post_chatrooms"),
    ]

    operations = [
        migrations.RemoveField(model_name="chatroom_post", name="chatrooms",),
        migrations.RemoveField(model_name="chatroom_post", name="posts",),
        migrations.RemoveField(model_name="post", name="chatrooms",),
        migrations.DeleteModel(name="Chatroom",),
        migrations.DeleteModel(name="Chatroom_Post",),
    ]
