# Generated by Django 4.1.6 on 2023-03-14 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0008_remove_chatroom_post_chatrooms_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chatroom",
            fields=[
                (
                    "name",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
                ("users", models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name="post", old_name="pub_date", new_name="date",
        ),
        migrations.RenameField(
            model_name="post", old_name="post_text", new_name="text",
        ),
        migrations.AddField(
            model_name="post",
            name="chatroom",
            field=models.ForeignKey(
                default="general",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="posts.chatroom",
            ),
            preserve_default=False,
        ),
    ]
