# Generated by Django 4.1.6 on 2023-03-14 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0009_chatroom_rename_pub_date_post_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post", old_name="text", new_name="post_text",
        ),
        migrations.RemoveField(model_name="post", name="chatroom",),
        migrations.DeleteModel(name="Chatroom",),
    ]
