# Generated by Django 4.1.6 on 2023-03-14 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0010_rename_text_post_post_text_remove_post_chatroom_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post", old_name="date", new_name="pub_date",
        ),
    ]
