# Generated by Django 4.1.6 on 2023-03-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0012_chatroom_post_chatroom"),
    ]

    operations = [
        migrations.AlterModelOptions(name="post", options={"ordering": ["pub_date"]},),
        migrations.AlterField(
            model_name="post", name="post_text", field=models.TextField(max_length=140),
        ),
    ]
