# Generated by Django 4.1.6 on 2023-03-22 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0016_alter_post_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="post_image",
            field=models.ImageField(null=True, upload_to="post-img"),
        ),
    ]
